### ISSUE TITLE
download.sh is not found.

### ISSUE THREAD

**Issue by betterhalfwzm** [mit-han-lab/amc-release#1]
Thank you for sharing the code. In the /checkpoints，I didn't find download.sh, Can you give me some information? And, when i run ./scripts/search_mobilenetv2_0.7flops.sh, a mistake was encountered, as follows:
~/AMC$ ./scripts/search_mobilenetv2_0.7flops.sh
=> Preparing data: imagenet...
=> Conv layers to share channels: [[4, 6], [8, 10, 12], [14, 16, 18, 20], [22, 24, 26]]
=> Prunable layer idx: [3, 11, 15, 21, 25, 31, 35, 41, 45, 51, 55, 61, 65, 71, 75, 81, 85, 91, 95, 101, 105, 111, 115, 121, 125, 131, 135, 141, 145, 151, 155, 161, 165, 171, 174, 179]
=> Buffer layer idx: [8, 18, 28, 38, 48, 58, 68, 78, 88, 98, 108, 118, 128, 138, 148, 158, 168]
=> Initial min strategy dict: {3: [1, 0.2], 11: [0.2, 0.2], 15: [0.2, 0.2], 21: [0.2, 0.2], 25: [0.2, 0.2], 31: [0.2, 0.2], 35: [0.2, 0.2], 41: [0.2, 0.2], 45: [0.2, 0.2], 51: [0.2, 0.2], 55: [0.2, 0.2], 61: [0.2, 0.2], 65: [0.2, 0.2], 71: [0.2, 0.2], 75: [0.2, 0.2], 81: [0.2, 0.2], 85: [0.2, 0.2], 91: [0.2, 0.2], 95: [0.2, 0.2], 101: [0.2, 0.2], 105: [0.2, 0.2], 111: [0.2, 0.2], 115: [0.2, 0.2], 121: [0.2, 0.2], 125: [0.2, 0.2], 131: [0.2, 0.2], 135: [0.2, 0.2], 141: [0.2, 0.2], 145: [0.2, 0.2], 151: [0.2, 0.2], 155: [0.2, 0.2], 161: [0.2, 0.2], 165: [0.2, 0.2], 171: [0.2, 0.2], 174: [0.2, 0.2], 179: [0.2, 1]}
=> Extracting information...
=> shape of embedding (n_layer * n_dim): (36, 10)
=> original acc: 97.067%
=> original weight size: 3.4708 M param
=> FLOPs:
[10.838016, 3.612672, 6.422528, 19.267584, 2.709504, 7.225344, 10.838016, 4.064256, 10.838016, 10.838016, 1.016064, 3.612672, 4.816896, 1.354752, 4.816896, 4.816896, 1.354752, 4.816896, 4.816896, 0.338688, 2.408448, 4.816896, 0.677376, 4.816896, 4.816896, 0.677376, 4.816896, 4.816896, 0.677376, 4.816896, 4.816896, 0.677376, 7.225344, 10.838016, 1.016064, 10.838016, 10.838016, 1.016064, 10.838016, 10.838016, 0.254016, 4.51584, 7.5264, 0.42336, 7.5264, 7.5264, 0.42336, 7.5264, 7.5264, 0.42336, 15.0528, 20.0704, 1.281]
=> original FLOPs: 300.7753 M
=> Saving logs to ./logs/mobilenetv2_imagenet_r0.7_search-run1
=> Output path: ./logs/mobilenetv2_imagenet_r0.7_search-run1...
** Actual replay buffer size: 3600
Traceback (most recent call last):
  File "amc_search.py", line 242, in <module>
    train(args.train_episode, agent, env, args.output)
  File "amc_search.py", line 122, in train
    observation2, reward, done, info = env.step(action)
  File "/home/wangzhaoming/AMC/env/channel_pruning_env.py", line 152, in step
    self.layer_embedding[self.cur_ind][-2] = sum(self.flops_list[self.cur_ind + 1:]) * 1. / self.org_flops  # rest
AttributeError: 'ChannelPruningEnv' object has no attribute 'flops_list'
Can it be solved? Thank you very much.

**Comment by tonylins** [comment]
Sorry for the mistake, we have added download.sh file. The `flops_list' bug has been fixed. 

Currently, the code only supports MobileNet-V1. Please run the V1 example. Thanks!

**Comment by tonylins** [comment]
The `flops_list' bug has been fixed. Sorry for the mistake!

**Comment by betterhalfwzm** [comment]
@tonylins Thank you for your reply. I'll try. And V2 code be released?
