### ISSUE TITLE
high compression ratio

### ISSUE THREAD

**Issue by HKLee2040** [mit-han-lab/amc-release#14]
I had tried to compress mobilenet v1 model  /w visual wake word dataset, the compression ratio can not too high, e.g. 7 times (or 14% of original model size), the accuracy drop is obvious.

However, I compress the model by two stage, i.e., 1st 25% and 2nd 56%, the accuracy can be kept  as high as original model and the total compression ratio could be 14%.

Does it mean that amc can't work well in high compression ratio?  Or I misunderstand your algorithm?  Do you have test high compression ratio case?

**Comment by tonylins** [comment]
Hi,

AMC uses the reconstructed weights to evaluate the performance. If the compress rate is too high, it may not get an accurate approximation. You may break the pruning into several stages or add fine-tuning after reconstruction.
