### ISSUE TITLE
Compress ProxlessNas

### ISSUE THREAD

**Issue by HKLee2040** [mit-han-lab/amc-release#18]
I'm trying to compress ProxlessNAS but met the following error.
where the model comes from 
model = torch.hub.load('mit-han-lab/ProxylessNAS', "proxyless_cpu", pretrained=True)

Could you please give me comments to fix the problem?

Error message:
  File "amc_search.py", line 262, in <module>
    train(args.train_episode, agent, env, args.output)
  File "amc_search.py", line 142, in train
    observation2, reward, done, info = env.step(action)
  File "/home/work/amc_vww_proxless/env/channel_pruning_env.py", line 97, in step
    action, d_prime, preserve_idx = self.prune_kernel(self.prunable_idx[self.cur_ind], action, preserve_idx)
  File "/home/work/amc_vww_proxless/env/channel_pruning_env.py", line 228, in prune_kernel
    masked_X = X[:, mask]
IndexError: boolean index did not match indexed array along dimension 1; dimension is 80 but corresponding boolean dimension is 40

**Comment by HKLee2040** [comment]
In this case, i.e., ProxlessNas, the GPU memory usage is accumulated at following code " _ = self.model(input_var)", and then out of memory...

        # now let the image flow
        print('=> Extracting information...')
        with torch.no_grad():
            for i_b, (input, target) in enumerate(self.train_loader):  # use image from train set
                if i_b == self.n_calibration_batches:
                    break
                self.data_saver.append((input.clone(), target.clone()))
                input_var = torch.autograd.Variable(input).cuda()

                # inference and collect stats
                _ = self.model(input_var)

**Comment by HKLee2040** [comment]
Find the problem. Close the issue.

**Comment by chaos1992** [comment]
@HKLee2040, could you tell me how did you solve this problem? I met the same problem
