### ISSUE TITLE
How does AMC validate the pruned model to get reward?

### ISSUE THREAD

**Issue by haibao-yu** [mit-han-lab/amc-release#19]
Hi, thanks for your great work!

However, I find that it always validate the original model under "train" mode.
In env.step(), it validates the model(line 123) to get the reward after prune_kernel() operation(line 97).
But the model will be pruned only under the "export" mode as line 249 to line 261.

So what's the problem?

**Comment by tonylins** [comment]
Hi, during the RL process, the kernel will be pseudo pruned by setting some weights to zero. It will produce the same result as the real pruning.
