### ISSUE TITLE
Current code only supports 1x1 conv？

### ISSUE THREAD

**Issue by zhangxinqian** [mit-han-lab/amc-release#3]

**Comment by tonylins** [comment]
Yes. Since the current code only runs on MobileNet-V1, where 1x1 conv is pruned. For other conv like 3x3, you can just conduct the post-pruning linear regression after im2col.

**Comment by RizhaoCai** [comment]
Hello.  'you can just conduct the post-pruning linear regression after im2col.' What do you mean by im2col? It seems that there is no such item called 'im2col'. What I need to do is modify the function 'prune_kernel'?
Any more suggestions for pruning 3x3 conv ?
