### ISSUE TITLE
Pruning for Object Detection tasks

### ISSUE THREAD

**Issue by RizhaoCai** [mit-han-lab/amc-release#4]
Hey. I notice that on the imagenet task, the accuracy of a model after pruning is used to calculate reward. In object detection scenarios, what do you use to calculate that? mAP, loss?

**Comment by tonylins** [comment]
For the object detection result in the paper, we simply fine-tuned the ImageNet pruned model on detection task. I think the performance could be better if you directly optimize for the object detection using the criterion like mAP or loss (each one should be OK but not sure which is better).
